services:
  frontend-nginx:
    image: mayowasam/frontend:v3   # new built image with frontend baked in
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
          cpus: "0.25"
    depends_on:
      - backend


  backend:
    image: mayowasam/backend:v1
    env_file: ./backend/.env
    command: >
      sh -c "until pg_isready -h postgres -p 5432 -U $POSTGRES_USER;
             do sleep 2; done &&
             npx prisma migrate deploy &&
             npx prisma generate &&
             npm start"
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/my_secret
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql
    secrets:
      - my_secret
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"


secrets:
  my_secret:
    file: ./secrets/secrets.txt

volumes:
  pgdata:
  frontend_build:
